/**
 * CI Pipeline Generator
 *
 * Reads the project's validator configuration and generates CI pipeline config
 * with the hardening pipeline pre-wired. Platform matches repoTool setting.
 *
 * Canonical Reference: .pi/architecture/modules/project-scaffolding-epic0.md#ci-generator
 * Last Sync: 2026-06-03
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { Language } from "./templates.js";

export interface CiPlan {
	files: { path: string; content: string }[];
}

/**
 * Generate CI pipeline configuration and stage scripts.
 */
export function generateCiPipeline(
	targetDir: string,
	options: {
		language: Language;
		buildTool?: "maven" | "gradle";
		repoTool: "gh" | "glab";
		validators: string[];
		dryRun?: boolean;
	},
): CiPlan {
	const { language, buildTool, repoTool, validators, dryRun } = options;
	const files: { path: string; content: string }[] = [];

	// Determine runner image based on language
	const runnerImage =
		language === "java"
			? buildTool === "gradle"
				? "gradle:8.5-jdk21"
				: "maven:3.9-eclipse-temurin-21"
			: "oven/bun:1";

	// Generate CI pipeline config
	if (repoTool === "gh") {
		const ciYaml = `name: CI
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ${runnerImage}
    steps:
      - uses: actions/checkout@v4
      - name: Run hardening pipeline
        run: bash .pi/scripts/ci/run_hardening_stages.sh
`;
		files.push({ path: path.join(targetDir, ".github/workflows/ci.yml"), content: ciYaml });
	} else {
		const ciYaml = `stages:
  - validate

validate:
  stage: validate
  image: ${runnerImage}
  script:
    - bash .pi/scripts/ci/run_hardening_stages.sh
  only:
    - branches
`;
		files.push({ path: path.join(targetDir, ".gitlab-ci.yml"), content: ciYaml });
	}

	// Generate stage scripts for each active validator (Issue #32)
	const stageScripts = generateStageScripts(language, validators);
	files.push(...stageScripts);

	if (!dryRun) {
		for (const file of files) {
			fs.mkdirSync(path.dirname(file.path), { recursive: true });
			fs.writeFileSync(file.path, file.content, "utf-8");
		}
	}

	return { files };
}

/**
 * Generate stage_*.sh scaffolding scripts for each active validator.
 */
function generateStageScripts(
	language: Language,
	validators: string[],
): { path: string; content: string }[] {
	const scripts: { path: string; content: string }[] = [];

	const stageMap: Record<string, { name: string; command: string }> = {
		ci: { name: "build", command: language === "java" ? "mvn clean compile -q" : "bun run build" },
		tests: { name: "test", command: language === "java" ? "mvn test -q" : "bun test" },
		architecture: { name: "architecture", command: "bash .pi/scripts/validate-architecture.sh" },
		security: {
			name: "security",
			command: language === "java" ? "mvn dependency-check:check -q" : "bun audit",
		},
		integration: {
			name: "integration",
			command: language === "java" ? "mvn verify -q" : "bun test --coverage",
		},
	};

	for (const validator of validators) {
		const stage = stageMap[validator];
		if (!stage) continue;

		const scriptContent = `#!/usr/bin/env bash
# ============================================================================
# stage_${stage.name}.sh — ${validator} validation stage
# Generated by Guardian Framework
# ============================================================================
set -euo pipefail

echo "============================================"
echo "  Stage: ${stage.name}"
echo "============================================"

echo "Running: ${stage.command}"
if ${stage.command}; then
    echo "✅ Stage ${stage.name} passed"
    exit 0
else
    echo "❌ Stage ${stage.name} failed"
    exit 1
fi
`;
		scripts.push({
			path: `.pi/scripts/ci/stage_${stage.name}.sh`,
			content: scriptContent,
		});
	}

	return scripts;
}
