#!/usr/bin/env bash
# ============================================================================
# stage_test.sh — tests validation stage
# Generated by Guardian Framework
# ============================================================================
set -euo pipefail

echo "============================================"
echo "  Stage: test"
echo "============================================"

echo "Running: mvn test -q"
if mvn test -q; then
    echo "✅ Stage test passed"
    exit 0
else
    echo "❌ Stage test failed"
    exit 1
fi
