#!/usr/bin/env bash
# ============================================================================
# stage_security.sh — security validation stage
# Generated by Guardian Framework
# ============================================================================
set -euo pipefail

echo "============================================"
echo "  Stage: security"
echo "============================================"

echo "  Running secret scan..."; for pattern in "sk-[A-Za-z0-9]{32,}" "ghp_[A-Za-z0-9]{36}" "AKIA[0-9A-Z]{16}" "BEGIN (RSA |EC )?PRIVATE KEY"; do grep -rE "$pattern" . --include="*.py" --include="*.ts" --include="*.tsx" --include="*.env" --include="*.yml" 2>/dev/null | grep -v ".git" | grep -v "node_modules" | grep -v ".pi" | head -1 | grep -q . && echo "  !! Potential secret detected: $pattern"; done; echo "  ✓ Secret scan complete"; echo "  Running dependency audit..."; if [[ -f "pom.xml" ]]; then command -v mvn &>/dev/null && mvn dependency-check:check -q 2>/dev/null || echo "  ⊘ Maven dep-check skipped"; elif [[ -f "package.json" ]]; then command -v npm &>/dev/null && npm audit --audit-level=high 2>/dev/null || echo "  ⊘ npm audit skipped"; elif [[ -f "Cargo.toml" ]]; then command -v cargo-audit &>/dev/null && cargo audit 2>/dev/null || echo "  ⊘ cargo-audit skipped"; else echo "  ⊘ No package manager found"; fi
echo "✅ Stage security passed"
exit 0
