#!/usr/bin/env bash
# ============================================================================
# stage_test.sh — tests validation stage
# Generated by Guardian Framework
# ============================================================================
set -euo pipefail

echo "============================================"
echo "  Stage: test"
echo "============================================"

if [[ -f "pom.xml" ]]; then echo "Running: mvn test"; mvn test -q; elif [[ -f "build.gradle" || -f "build.gradle.kts" ]]; then echo "Running: gradle test"; gradle test -q; elif [[ -f "package.json" ]]; then if command -v bun &>/dev/null; then echo "Running: bun test"; bun test; elif command -v npm &>/dev/null; then echo "Running: npm test"; npm test; else echo "⊘ No JS runner found"; fi; elif [[ -f "pyproject.toml" ]] && command -v pytest &>/dev/null; then echo "Running: pytest"; pytest -v; elif [[ -f "Cargo.toml" ]]; then echo "Running: cargo test"; cargo test; elif [[ -f "go.mod" ]]; then echo "Running: go test ./..."; go test ./...; else echo "⊘ No test config found, skipping."; fi
echo "✅ Stage test passed"
exit 0
